In [26]:
import numpy as np

In [27]:
x = np.array([0,1,2,3])
x

array([0, 1, 2, 3])

In [28]:
w = np.array([[0,1,2,3],[4,5,6,7]])
w


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
# play with np.arange()
g = np.arange(5,51,5, dtype=float)
g

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [30]:
# play with np.reshape()
h = np.reshape(g,(2,5),order='C')
h

array([[ 5., 10., 15., 20., 25.],
       [30., 35., 40., 45., 50.]])

In [32]:
# initialize array
x = np.array([0,1,2,3])

# square
print(np.square(x))

# square root
print(np.sqrt(x))

# cosine
print(np.cos(x))


[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [34]:
# initialize array
x = np.array([0,1,2,3])

# max value
print(np.max(x))

# min value
print(np.min(x))

# mean value
print(np.mean(x))

# standard div
print(np.std(x))

3
0
1.5
1.118033988749895
